# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "riscvm"

[options]
RISCVM_DIRECT_DISPATCH = false
RISCVM_CODE_ENCRYPTION = true
RISCVM_OPCODE_SHUFFLING = true
RISCVM_DEBUG_SYSCALLS = true

[target.riscvm]
type = "executable"
sources = ["main.cpp", "riscvm.cpp"]
headers = ["riscvm.h", "opcodes.h", "shuffled_opcodes.h", "trace.h"]
compile-features = ["cxx_std_17"]
RISCVM_DIRECT_DISPATCH.compile-definitions = ["DIRECT_DISPATCH"]
RISCVM_CODE_ENCRYPTION.compile-definitions = ["CODE_ENCRYPTION"]
RISCVM_OPCODE_SHUFFLING.compile-definitions = ["OPCODE_SHUFFLING"]
RISCVM_DEBUG_SYSCALLS.compile-definitions = ["DEBUG_SYSCALLS"]
clang-cl.compile-options = ["/clang:-fno-jump-tables", "/clang:-mno-sse"]
clang.compile-options = ["-fno-jump-tables", "-mno-sse"]
msvc.link-options = ["/DYNAMICBASE:NO", "/INCREMENTAL:NO"]

[target.tests]
type = "executable"
sources = ["tests.cpp", "riscvm.cpp"]
compile-features = ["cxx_std_17"]
compile-definitions = ["DEBUG_SYSCALLS"]
msvc.link-options = ["/DYNAMICBASE:NO", "/INCREMENTAL:NO"]

# Only for IDE purposes, not actually built here
[target.riscvm-crt0]
type = "custom"
sources = ["lib/crt0.c"]
